name: .NET CI

# Trigger on push or pull request to master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Restore dependencies for all .csproj files
      - name: Restore dependencies
        run: dotnet restore **/*.csproj

      # Build all projects in Release mode
      - name: Build
        run: dotnet build --configuration Release --no-restore **/*.csproj

      # Run tests in all test projects
      - name: Run tests
        run: dotnet test "SmartPlantBuddies.Tests/SmartPlantBuddies.Tests.csproj"--configuration Release --no-build --verbosity normal **/*.csproj
